"""
Recommendation routes for ESO Build Optimizer API.

Handles generation and retrieval of build recommendations by delegating
percentile calculation and recommendation generation to the ML pipeline
via the adapter layer.
"""

import logging
from typing import Annotated
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy import and_, select
from sqlalchemy.ext.asyncio import AsyncSession

from api.core.security import CurrentUser
from api.models.database import CombatRun, Recommendation, get_db
from api.models.schemas import (
    ErrorResponse,
    RecommendationCategory,
    RecommendationResponse,
    RecommendationsListResponse,
)
from ml.adapter import MLAdapter

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/runs", tags=["Recommendations"])

# Singleton adapter instance (thread-safe, stateless after init)
_ml_adapter = MLAdapter()


# =============================================================================
# Shared DB Queries
# =============================================================================

async def _fetch_run_with_auth(
    run_id: UUID,
    current_user: CurrentUser,
    db: AsyncSession,
) -> CombatRun:
    """Fetch a combat run and verify ownership."""
    result = await db.execute(
        select(CombatRun).where(CombatRun.run_id == run_id)
    )
    run = result.scalar_one_or_none()

    if not run:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Combat run not found",
        )

    if run.player_id != current_user.id:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Access denied to this combat run",
        )

    return run


async def _fetch_similar_runs(
    run: CombatRun,
    db: AsyncSession,
    limit: int = 1000,
) -> list[CombatRun]:
    """Find similar runs for percentile comparison.

    Similarity criteria:
    - Same content (dungeon name + difficulty)
    - Similar CP level (+/- 200)
    """
    similar_query = (
        select(CombatRun)
        .where(
            and_(
                CombatRun.content_name == run.content_name,
                CombatRun.difficulty == run.difficulty,
                CombatRun.cp_level.between(run.cp_level - 200, run.cp_level + 200),
                CombatRun.run_id != run.run_id,
            )
        )
        .limit(limit)
    )

    result = await db.execute(similar_query)
    return list(result.scalars().all())


# =============================================================================
# Get Recommendations for Run
# =============================================================================

@router.get(
    "/{run_id}/recommendations",
    response_model=RecommendationsListResponse,
    responses={
        200: {"description": "Recommendations for the run"},
        401: {"description": "Not authenticated", "model": ErrorResponse},
        403: {"description": "Access denied", "model": ErrorResponse},
        404: {"description": "Run not found", "model": ErrorResponse},
    },
    summary="Get recommendations for a run",
    description="Get AI-generated recommendations to improve performance based on a combat run.",
)
async def get_recommendations(
    run_id: UUID,
    current_user: CurrentUser,
    db: Annotated[AsyncSession, Depends(get_db)],
    regenerate: bool = Query(
        False,
        description="Force regeneration of recommendations",
    ),
) -> RecommendationsListResponse:
    """
    Get recommendations for a specific combat run.

    Recommendations are generated by the ML pipeline, comparing the run's
    metrics against similar runs and identifying areas for improvement.

    Set regenerate=true to force new recommendations even if cached ones exist.
    """
    run = await _fetch_run_with_auth(run_id, current_user, db)

    # Check for existing recommendations (cache hit)
    if not regenerate:
        existing_result = await db.execute(
            select(Recommendation)
            .where(Recommendation.run_id == run_id)
            .order_by(Recommendation.priority)
        )
        existing_recs = existing_result.scalars().all()

        if existing_recs:
            # Still need percentiles for the response
            similar_runs = await _fetch_similar_runs(run, db)
            percentiles, sample_size, confidence = await _ml_adapter.calculate_percentiles_only(
                run, similar_runs
            )
            return RecommendationsListResponse(
                run_id=run_id,
                recommendations=[
                    RecommendationResponse(
                        recommendation_id=rec.recommendation_id,
                        run_id=rec.run_id,
                        category=RecommendationCategory(rec.category),
                        priority=rec.priority,
                        current_state=rec.current_state,
                        recommended_change=rec.recommended_change,
                        expected_improvement=rec.expected_improvement,
                        reasoning=rec.reasoning,
                        confidence=rec.confidence,
                    )
                    for rec in existing_recs
                ],
                percentiles=percentiles,
                sample_size=sample_size,
                confidence=confidence,
            )

    # Fetch similar runs and run full ML analysis
    similar_runs = await _fetch_similar_runs(run, db)
    percentiles, sample_size, confidence, rec_dicts = await _ml_adapter.analyze_run(
        run, similar_runs
    )

    # Delete old recommendations if regenerating
    if regenerate:
        await db.execute(
            Recommendation.__table__.delete().where(
                Recommendation.run_id == run_id
            )
        )

    # Persist new recommendations
    new_recommendations = []
    for rec_dict in rec_dicts:
        db_rec = Recommendation(
            run_id=run.run_id,
            **rec_dict,
        )
        db.add(db_rec)
        new_recommendations.append(db_rec)

    await db.commit()

    for rec in new_recommendations:
        await db.refresh(rec)

    return RecommendationsListResponse(
        run_id=run_id,
        recommendations=[
            RecommendationResponse(
                recommendation_id=rec.recommendation_id,
                run_id=rec.run_id,
                category=RecommendationCategory(rec.category),
                priority=rec.priority,
                current_state=rec.current_state,
                recommended_change=rec.recommended_change,
                expected_improvement=rec.expected_improvement,
                reasoning=rec.reasoning,
                confidence=rec.confidence,
            )
            for rec in new_recommendations
        ],
        percentiles=percentiles,
        sample_size=sample_size,
        confidence=confidence,
    )


# =============================================================================
# Get Percentiles Only
# =============================================================================

class PercentilesResponse(RecommendationsListResponse):
    """Response for percentiles endpoint."""
    pass


@router.get(
    "/{run_id}/percentiles",
    response_model=PercentilesResponse,
    responses={
        200: {"description": "Percentiles for the run"},
        401: {"description": "Not authenticated", "model": ErrorResponse},
        403: {"description": "Access denied", "model": ErrorResponse},
        404: {"description": "Run not found", "model": ErrorResponse},
    },
    summary="Get percentiles for a run",
    description="Get percentile rankings compared to similar runs without generating recommendations.",
)
async def get_percentiles(
    run_id: UUID,
    current_user: CurrentUser,
    db: Annotated[AsyncSession, Depends(get_db)],
) -> PercentilesResponse:
    """
    Get percentile rankings for a combat run.

    Compares the run against similar runs (same content, similar CP level)
    to determine where the player ranks.
    """
    run = await _fetch_run_with_auth(run_id, current_user, db)
    similar_runs = await _fetch_similar_runs(run, db)

    percentiles, sample_size, confidence = await _ml_adapter.calculate_percentiles_only(
        run, similar_runs
    )

    return PercentilesResponse(
        run_id=run_id,
        recommendations=[],
        percentiles=percentiles,
        sample_size=sample_size,
        confidence=confidence,
    )


# =============================================================================
# Leaderboard Types (for future implementation)
# =============================================================================

class LeaderboardEntry(RecommendationResponse):
    """Leaderboard entry with player info."""
    rank: int
    character_name: str
    dps: float
    content_name: str
    difficulty: str


class LeaderboardResponse(RecommendationsListResponse):
    """Response for leaderboard endpoint."""
    entries: list[LeaderboardEntry]
    content_name: str
    difficulty: str
